export enum ProductSettingPropertyKey {
  CODE_GENERATION_PATTERN = 'CODE_GENERATION_PATTERN',
  CODE_GENERATION_SUFFIX = 'CODE_GENERATION_SUFFIX',
  CODE_GENERATION_PREFIX = 'CODE_GENERATION_PREFIX',
  CODE_GENERATION_COUNTER = 'CODE_GENERATION_COUNTER',
  CODE_GENERATION_COUNTER_PADDING = 'CODE_GENERATION_COUNTER_PADDING',
  CODE_GENERATION_MAX_ATTEMPTS = 'CODE_GENERATION_MAX_ATTEMPTS',
}
